### PR TITLE
make `folder2ctx` into cli

### PR DESCRIPTION
**Pull request by hamelsmu**
`folder2ctx` is pretty cool.  I want to use it everywhere for quick things.  This small change was needed to allow me to use it as a CLI.   

Please let me know if this modification is acceptible.

### CODE REVIEW

**Comment by jph00** [comment]
Thanks @hamelsmu ! One deficiency of call_parse is that decorated functions are harder to use as plain functions -- so instead could you create a `folder2ctx_cli` function with the decorator that calls the current function, using delegates to pass along kwargs? And maybe hide it from the docs since that py function itself isn't of much interest.

**Comment by hamelsmu** [comment]
@jph00 I tried to completely delegate `folder2ctx_cli` to `folder2ctx`, but that didn't seem to work for me, perhaps because `folder2ctx` has a delegate as well?  I'm not completely sure why.

Like this didn't work:

```python
@call_parse
@delegates(folder2ctx)
def folder2ctx_cli(
    **kwargs # Passed to `folder2ctx`
)->str: # XML for Claude context
    return folder2ctx(**kwargs)
```

So the change I just pushed gets as close as I can get, however let me know if you have another idea.

**Comment by jph00** [comment]
Thanks Hamel! :D

**Comment by jph00** [comment]
I removed the 'prefix' arg fyi. kwargs handles that fine.

**Pull request merged**
