### PR TITLE
Migrate call_func from claudette to toolslm

### PR DESCRIPTION
**Pull request by ncoop57**
This PR migrates the call_func logic from claudette to toolslm in order to help with reusability of tool calling across our various LLM API wrappers like cosette. Some changes were made to properly abstract away the specifics of each API provider.

Specifically, call_func now takes in the function name, the function parameters, and a namespace which is required.

```python
def call_func(fc_name, fc_inputs, ns):
    "Call the function `fc_name` with the given `fc_inputs` using namespace `ns`."
    if not isinstance(ns, abc.Mapping): ns = mk_ns(*ns)
    func = ns[fc_name]
    return func(**fc_inputs)
```

Previously, the namespace (if given as 'none') would be created based on globals. However, since imported modules have their own separate namespace from the importer of the module, you would end up missing keys. Therefore, I think it's better to require the caller to actually define the namespace that is going to be searched.

I also moved the helper function for making a namespace given a list of items to here, along with a new function called obj2ns which handles converting objects (like classes) into a proper namespace object.

```python
def obj2ns(obj): return {n: getattr(obj,n) for n,_ in inspect.getmembers(obj.__class__,inspect.isfunction)}

class Dummy:
    def subs(self,a:int,b:int=1) -> int: return a - b
d = Dummy()

ns = obj2ns(d); ns
# OUTPUT:
# {'subs': <bound method Dummy.subs of <__main__.Dummy object at 0x105870ee0>>}
```

Previously this was handled differently with class objects where we would only attempt to get the attribute of the object's functions if it existed.

```python
def call_func(fc:ToolUseBlock, # Tool use block from Claude's message
              ns:Optional[abc.Mapping]=None, # Namespace to search for tools, defaults to `globals()`
              obj:Optional=None # Object to search for tools
             ):
    "Call the function in the tool response `tr`, using namespace `ns`."
    if ns is None: ns=globals()
    if not isinstance(ns, abc.Mapping): ns = _mk_ns(*ns)
    func = getattr(obj, fc.name, None)
    if not func: func = ns[fc.name]
    return func(**fc.input)
```

However, I felt that we could abstract this away just into the general concept of having namespaces where we convert objects to namespaces. This simplifies the code greatly, especially when modifying, for example, Claudette to now use this API.

### CODE REVIEW

**Comment by jph00** [comment]
Did you still want me to review this now @ncoop57 ?

**Comment by ncoop57** [comment]
@jph00 no not yet sorry. Need to redesign a bit after our convl

**Comment by ncoop57** [comment]
Okay, @jph00 it should be good for you to review now. I removed the function `obj2ns` and moved the logic into `mk_ns` to make it cleaner.

**Comment by jph00** [comment]
Super job @ncoop57 ! :D Also I forgot that the pipe operator was added for dictionaries in Python 3.9, which is now the oldest non-EOL version of Python, so we can safely use them! Very exciting. :D

**Pull request merged**
